import { useEffect, useState } from 'react'
import { Bell, Bookmark, BriefcaseBusiness, ChevronDown, Clock3, Filter, LayoutDashboard, MapPin, Menu, Moon, Plus, Search, Settings2, Sparkles, Sun, Users, X } from 'lucide-react'
import './App.css'

type Role = 'seeker' | 'recruiter'
const jobs = [
  { id: 1, company: 'Northstar Labs', logo: 'N', color: 'coral', title: 'Product Designer', location: 'Remote · United States', salary: '$120k – $155k', type: 'Full-time', posted: '2h ago', tags: ['Figma', 'Design systems', 'SaaS'], featured: true },
  { id: 2, company: 'Morrow Health', logo: 'M', color: 'blue', title: 'Senior Product Manager', location: 'New York, NY · Hybrid', salary: '$145k – $180k', type: 'Full-time', posted: '5h ago', tags: ['Strategy', 'B2B', 'Health tech'], featured: false },
  { id: 3, company: 'Orbit Finance', logo: 'O', color: 'mint', title: 'Frontend Engineer', location: 'Remote · Americas', salary: '$130k – $165k', type: 'Full-time', posted: '1d ago', tags: ['React', 'TypeScript', 'GraphQL'], featured: false },
  { id: 4, company: 'Common Ground', logo: 'C', color: 'violet', title: 'Content Marketing Lead', location: 'Austin, TX · On-site', salary: '$95k – $120k', type: 'Full-time', posted: '1d ago', tags: ['Editorial', 'SEO', 'Brand'], featured: false },
]
const applications = [
  { company: 'Morrow Health', title: 'Senior Product Manager', status: 'Interview', date: 'Applied Aug 27', tone: 'green' },
  { company: 'Orbit Finance', title: 'Frontend Engineer', status: 'Under review', date: 'Applied Aug 24', tone: 'amber' },
  { company: 'Common Ground', title: 'Content Marketing Lead', status: 'Application sent', date: 'Applied Aug 19', tone: 'gray' },
]

function App() {
  const [role, setRole] = useState<Role>('seeker')
  const [query, setQuery] = useState('')
  const [saved, setSaved] = useState<number[]>([2])
  const [applied, setApplied] = useState<number[]>([2, 3, 4])
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeNav, setActiveNav] = useState('Find jobs')
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('juncture-theme') === 'dark')
  useEffect(() => {
    document.documentElement.dataset.theme = darkMode ? 'dark' : 'light'
    localStorage.setItem('juncture-theme', darkMode ? 'dark' : 'light')
  }, [darkMode])
  const visibleJobs = jobs.filter((job) => `${job.title} ${job.company} ${job.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  const toggleSaved = (id: number) => setSaved((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const toggleApplied = (id: number) => setApplied((current) => current.includes(id) ? current : [...current, id])

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">j</span><span>juncture</span></div><div className="role-switch"><button className={role === 'seeker' ? 'selected' : ''} onClick={() => setRole('seeker')}>Job seeker</button><button className={role === 'recruiter' ? 'selected' : ''} onClick={() => setRole('recruiter')}>Recruiter</button></div><div className="top-actions"><button className="icon-button" onClick={() => setDarkMode(!darkMode)} aria-label={darkMode ? 'Switch to light theme' : 'Switch to dark theme'} title={darkMode ? 'Switch to light theme' : 'Switch to dark theme'}>{darkMode ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-button" aria-label="Notifications"><Bell size={18} /><span className="notification-dot" /></button><button className="profile-button" onClick={() => setMenuOpen(!menuOpen)}><span className="avatar">AM</span><span className="profile-name">Alex Morgan</span><ChevronDown size={15} /></button>{menuOpen && <div className="profile-menu"><strong>Alex Morgan</strong><span>alex@juncture.co</span><button>Account settings</button><button>Sign out</button></div>}</div><button className="mobile-menu icon-button" aria-label="Open menu"><Menu size={20} /></button></header>
    <div className="workspace"><aside className="sidebar"><div className="sidebar-label">Workspace</div>{(role === 'seeker' ? [['Find jobs', Search], ['My applications', BriefcaseBusiness], ['Saved jobs', Bookmark]] : [['Overview', LayoutDashboard], ['Jobs posted', BriefcaseBusiness], ['Talent pool', Users]]).map(([label, Icon]) => <button key={label as string} className={`nav-item ${activeNav === label ? 'active' : ''}`} onClick={() => setActiveNav(label as string)}><Icon size={18} /><span>{label as string}</span>{label === 'My applications' && <span className="nav-count">3</span>}</button>)}<div className="sidebar-divider" /><button className="nav-item"><Settings2 size={18} /><span>Settings</span></button><div className="sidebar-bottom"><div className="upgrade-kicker"><Sparkles size={15} /> Pro workspace</div><strong>Make every hire count.</strong><p>Unlock candidate insights and team collaboration.</p><button>Explore Pro <span>→</span></button></div></aside>
      <main className="main-content">{role === 'seeker' ? <><section className="page-intro"><div><p className="eyebrow">MONDAY, SEPTEMBER 04, 2026</p><h1>Good morning, Alex <span>✦</span></h1><p className="intro-copy">Your next opportunity is closer than you think.</p></div><button className="resume-button">Update resume <span>↗</span></button></section><section className="search-panel"><div className="search-field"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Job title, skill, or company" />{query && <button className="clear-search" onClick={() => setQuery('')}><X size={16} /></button>}</div><div className="search-field location"><MapPin size={18} /><input placeholder="Location or remote" /></div><button className="search-button"><Search size={18} /> Search jobs</button></section><div className="content-header"><div><h2>Recommended for you</h2><p>Curated from your skills and preferences</p></div><button className="filter-button"><Filter size={16} /> Filters <span className="filter-count">2</span></button></div><div className="job-list">{visibleJobs.map((job) => <article className={`job-card ${job.featured ? 'featured' : ''}`} key={job.id}><div className={`company-logo ${job.color}`}>{job.logo}</div><div className="job-info"><div className="job-meta"><span>{job.company}</span>{job.featured && <span className="featured-label">Featured</span>}<span className="posted">{job.posted}</span></div><h3>{job.title}</h3><div className="job-details"><span><MapPin size={14} />{job.location}</span><span><BriefcaseBusiness size={14} />{job.type}</span><span className="salary">{job.salary}</span></div><div className="tag-row">{job.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="job-actions"><button className={`save-button ${saved.includes(job.id) ? 'saved' : ''}`} onClick={() => toggleSaved(job.id)} aria-label="Save job"><Bookmark size={18} fill={saved.includes(job.id) ? 'currentColor' : 'none'} /></button><button className={`apply-button ${applied.includes(job.id) ? 'applied' : ''}`} onClick={() => toggleApplied(job.id)}>{applied.includes(job.id) ? 'Applied' : 'Apply now'} {!applied.includes(job.id) && <span>→</span>}</button></div></article>)}</div><section className="applications-section"><div className="content-header"><div><h2>Application activity</h2><p>Stay close to your next yes</p></div><button className="text-button">View all <span>→</span></button></div><div className="application-list">{applications.map((application) => <div className="application-row" key={application.company}><div className="mini-logo">{application.company[0]}</div><div className="application-title"><strong>{application.title}</strong><span>{application.company} · {application.date}</span></div><span className={`status ${application.tone}`}>{application.status}</span><Clock3 size={16} className="clock" /></div>)}</div></section></> : <RecruiterView />}</main></div>
  </div>
}

function RecruiterView() { return <><section className="page-intro recruiter-intro"><div><p className="eyebrow">RECRUITER WORKSPACE</p><h1>Build your next great team.</h1><p className="intro-copy">A clear view of your open roles and the people behind every application.</p></div><button className="post-button"><Plus size={18} /> Post a job</button></section><div className="metric-grid"><div className="metric-card"><span>Open roles</span><strong>08</strong><small className="positive">↑ 2 this month</small></div><div className="metric-card"><span>Total applications</span><strong>248</strong><small className="positive">↑ 18% vs last month</small></div><div className="metric-card"><span>Avg. time to hire</span><strong>19 <em>days</em></strong><small className="positive">↓ 3 days faster</small></div></div><section className="recruiter-section"><div className="content-header"><div><h2>Your open roles</h2><p>Track performance and manage your pipeline</p></div><button className="filter-button"><Filter size={16} /> All roles <ChevronDown size={14} /></button></div><div className="recruiter-table"><div className="table-head"><span>ROLE</span><span>APPLICANTS</span><span>STATUS</span><span>POSTED</span><span /></div>{[['Senior Product Manager','Morrow Health','64','12 new','Aug 28','blue'],['Frontend Engineer','Orbit Finance','42','8 new','Aug 21','mint'],['Product Designer','Northstar Labs','31','5 new','Aug 18','coral'],['Content Marketing Lead','Common Ground','18','2 new','Aug 12','violet']].map(([title, company, count, fresh, date, color]) => <div className="table-row" key={title}><div className="role-cell"><div className={`company-logo small ${color}`}>{company[0]}</div><div><strong>{title}</strong><span>{company}</span></div></div><div className="applicant-count"><strong>{count}</strong><span>{fresh}</span></div><span className="status green">Active</span><span className="table-date">{date}</span><button className="more-button">•••</button></div>)}</div></section><section className="recruiter-section recent-section"><div className="content-header"><div><h2>Recent candidate activity</h2><p>The latest movement across your roles</p></div><button className="text-button">View pipeline <span>→</span></button></div><div className="candidate-card"><div className="candidate-avatar">JR</div><div><strong>Jordan Rivera</strong><span>Applied for Senior Product Manager</span></div><span className="candidate-time">24 min ago</span><button className="review-button">Review profile</button></div></section></> }

export default App
